# Estatística e Python para Iniciantes
Este notebook é um guia passo a passo para quem está a começar do zero. Vamos aprender conceitos básicos de estatística e como os aplicar usando Python.

## O que é estatística?
A estatística é a ciência que coleta, organiza, analisa e interpreta dados para auxiliar na tomada de decisões e previsão de eventos. Utiliza métodos matemáticos e probabilísticos para transformar dados brutos em informações úteis.
Na estatística temos variaveis, uma **variável** (em estatística) é qualquer característica que pode ser medida ou contada. Dividem-se em dois grandes grupos:
* **Variáveis Qualitativas (ou Categóricas):** Representam qualidades, rótulos ou categorias. Não são números com os quais fazemos contas matemáticas. Exemplo: cor dos olhos, cidade de residência, género.
* **Variáveis Quantitativas (ou Numéricas):** Representam quantidades e números reais. Exemplo: idade, salário, altura, número de filhos.

Para entender melhor os conceitos vamos analisar alguns dados

## Carregando e manipulando dados:
Para trabalhar com dados em Python, usamos uma biblioteca chamada **Pandas**. As vezes algumas bibliotecas não estão instaladas no seu ambiente conda para isso vamos usar o comando `%pip install pandas`

EXERCÍCIO:
Pesquise sobre a biblioteca pandas e escreva brevemente o que essa biblioteca faz:

SUA RESPOSTA:

In [24]:
%pip install pandas # instalando a biblioteca pandas, caso ainda não esteja instalada
import pandas as pd # importando a biblioteca e dando um apelido para ela, no resto do código, usaremos pd para acessar as funções da biblioteca pandas.

Requirement already satisfied: pandas in /home/carolina/miniconda3/lib/python3.13/site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in /home/carolina/miniconda3/lib/python3.13/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/carolina/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/carolina/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Para conseguir trabalhar com os dados vamos os transformar em um dataset. Um **dataset** (conjunto de dados) é como uma tabela do Excel. Tem linhas (que representam cada registo ou indivíduo) e colunas (que representam as características que recolhemos).

In [ ]:
df = pd.read_csv('02_dados.csv', index_col=False) # Lendo o arquivo csv e armazenando em um dataframe chamado df. 
df.head(10)  # comando para mostrar as 10 primeiras linhas do dataframe

,Horas_de_Estudo,Frequência,Envolvimento_dos_Pais,Acesso_a_Recursos,Atividades_Extracurriculares,Horas_de_Sono,Notas_Anteriores,Nível_de_Motivação,Acesso_à_Internet,Aulas_de_Reforço,Renda_Familiar,Qualidade_dos_Professores,Tipo_de_Escola,Influência_dos_Colegas,Atividade_Física,Dificuldades_de_Aprendizagem,Nível_de_Escolaridade_dos_Pais,Distância_de_Casa,Sexo,Nota_na_Prova
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
5,19,88,Medium,Medium,Yes,8,89,Medium,Yes,3,Medium,Medium,Public,Positive,3,No,Postgraduate,Near,Male,71
6,29,84,Medium,Low,Yes,7,68,Low,Yes,1,Low,Medium,Private,Neutral,2,No,High School,Moderate,Male,67
7,25,78,Low,High,Yes,6,50,Medium,Yes,1,High,High,Public,Negative,2,No,High School,Far,Male,66
8,17,94,Medium,High,No,6,80,High,Yes,0,Medium,Low,Private,Neutral,1,No,College,Near,Male,69
9,23,98,Medium,Medium,Yes,8,71,Medium,Yes,0,High,High,Public,Positive,5,No,High School,Moderate,Male,72

O dataset mostra informações de alunos e suas notas em uma prova.

EXERCÍCIO:
Usando o comando print(df.columns) veja todas as colunas que existem no dataset e as divida entre Variáveis Qualitativas e Variáveis Quantitativas.

In [13]:
print(df.columns)

Index(['Horas_de_Estudo', 'Frequência', 'Envolvimento_dos_Pais',
       'Acesso_a_Recursos', 'Atividades_Extracurriculares', 'Horas_de_Sono',
       'Notas_Anteriores', 'Nível_de_Motivação', 'Acesso_à_Internet',
       'Aulas_de_Reforço', 'Renda_Familiar', 'Qualidade_dos_Professores',
       'Tipo_de_Escola', 'Influência_dos_Colegas', 'Atividade_Física',
       'Dificuldades_de_Aprendizagem', 'Nível_de_Escolaridade_dos_Pais',
       'Distância_de_Casa', 'Sexo', 'Nota_na_Prova'],
      dtype='str')

SUA RESPOSTA:

Muitas vezes, não queremos analisar todo o dataset, mas apenas um grupo específico. O Pandas nos permite criar um "filtro". No exemplo abaixo, vamos separar apenas os registos onde a coluna 'Horas_de_Estudo' é maior ou igual a 30.

In [14]:
df[df['Horas_de_Estudo'] >= 30]

,Horas_de_Estudo,Frequência,Envolvimento_dos_Pais,Acesso_a_Recursos,Atividades_Extracurriculares,Horas_de_Sono,Notas_Anteriores,Nível_de_Motivação,Acesso_à_Internet,Aulas_de_Reforço,Renda_Familiar,Qualidade_dos_Professores,Tipo_de_Escola,Influência_dos_Colegas,Atividade_Física,Dificuldades_de_Aprendizagem,Nível_de_Escolaridade_dos_Pais,Distância_de_Casa,Sexo,Nota_na_Prova
31,31,70,Medium,High,Yes,7,66,Medium,Yes,1,High,Medium,Public,Negative,3,No,College,Near,Male,69
106,31,100,Medium,Medium,No,7,59,Medium,Yes,2,High,High,Public,Positive,5,No,Postgraduate,Moderate,Male,76
113,35,99,High,High,Yes,7,85,Low,Yes,2,Medium,High,Private,Neutral,2,No,Postgraduate,Near,Female,79
125,33,70,Medium,Medium,Yes,6,82,Low,Yes,1,Low,High,Public,Neutral,4,No,College,Near,Male,69
156,31,92,Medium,Medium,Yes,4,76,Medium,Yes,2,Medium,High,Public,Positive,4,Yes,High School,Far,Male,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1911,33,93,High,High,Yes,7,98,Low,Yes,0,Medium,Medium,Public,Negative,2,Yes,High School,Near,Female,74
1924,32,88,Medium,Low,Yes,7,83,Low,Yes,1,Low,High,Private,Positive,4,No,Postgraduate,Near,Male,73
1929,32,68,High,High,No,10,84,Medium,Yes,0,Medium,High,Private,Positive,2,No,Postgraduate,Far,Male,70
1934,36,68,Medium,Medium,Yes,8,74,High,Yes,2,Medium,Medium,Public,Negative,3,No,High School,Near,Male,70
1957,39,97,High,High,Yes,10,91,Medium,Yes,2,Low,Medium,Public,Positive,3,No,High School,Moderate,Female,79

EXERCÍCIO:
Faça um filtro para mostrar todas as linhas onde Atividades_Extracurriculares foram descritas como sim:

In [7]:
# SUA RESPOSTA

## Estatística Descritiva Básica
A estatística descritiva é o ramo da estatística que organiza, resume e apresenta dados brutos para torná-los compreensíveis, identificando padrões, tendências e variações. Ela não realiza inferências sobre populações maiores, focando apenas no conjunto de dados analisado através de medidas de resumo (média, mediana, moda), dispersão (desvio padrão, variância) e visualização gráfica.

#### O que é o Espaço Amostral?
Na estatística, o **espaço amostral** é simplesmente o conjunto de *todos os resultados possíveis* de uma variável ou de uma experiência. Se você jogar um dado normal de 6 faces, o espaço amostral (ou resultados possíveis) dele ao cair são: `[1, 2, 3, 4, 5, 6]`. Se jogar uma moeda o espaço amostral é `[Cara, Coroa]`.

EXERCÍCIO:
No nosso dataset, qual é o espaço amostral da variável qualitativa 'Dificuldades_de_Aprendizagem' e do 'Nível_de_Escolaridade_dos_Pais'?

SUA RESPOSTA:

Quando temos variaveis quantitativas é possivel ordenar os valores do maior para o menor, ou outros tipos de organizações.

EXERCÍCIO:
Identifique a menor e maior Nota_na_Prova do dataset.

In [ ]:
# SUA RESPOSTA

Quando temos uma variável quantitativa com muitos números, precisamos a resumir para tirar algumas conclusões. Usamos as "Medidas de Tendência Central"(Onde os dados se concentram ou medidas de resumo) para encontrar o valor que melhor representa o grupo:

EXERCÍCIO:
Pesquise e escreva com suas palavras o que é cada uma dessas Medidas de Tendência Central.

SUA RESPOSTA

* **Média:** 

* **Mediana:** 

* **Moda:**

Agora vamos calcular as medidas para as Horas_de_Sono dos alunos no nosso dataset.

In [19]:
media = df['Horas_de_Sono'].mean() # calculando a média da coluna 'Horas_de_Sono'

mediana = df['Horas_de_Sono'].median() # calculando a mediana da coluna 'Horas_de_Sono'

moda = df['Horas_de_Sono'].mode()[0] # calculando a moda da coluna 'Horas_de_Sono'

print("Média:",media)
print("Mediana:",mediana)
print("Moda:",moda)

Média: 6.9985
Mediana: 7.0
Moda: 7

EXERCÍCIO:
Agora calcule as medidas para as colunas: Horas_de_Estudo, Frequência e Notas_Anteriores.

In [ ]:
# SUA RESPOSTA