# Análise Exploratória de Dados (EDA)
A Análise Exploratória de Dados (EDA, na sigla em inglês) consiste em compreender os conjuntos de dados resumindo suas principais características, frequentemente por meio de representações gráficas. Essa etapa é crucial, especialmente na modelagem dos dados para aplicação de aprendizado de máquina. Através do processo de EDA, podemos definir o problema ou a definição do nosso conjunto de dados.
### Como fazer uma Análise Exploratória de Dados? 
A resposta é: depende do conjunto de dados com o qual você está trabalhando. Não existe um único método ou jeito para realizar a EDA, mas agora você vai aprender alguns métodos e gráficos comuns que podem ser usados ​​no processo de EDA.

In [1]:
# importando Bibliotecas
import pandas as pd
import numpy as np
import plotly.express as px

%pip install nbformat  # lembra para que serve essa linha?

# Se existir erro ao tentar rodar a célula lembre-se é necessário instalar as bibliotecas no seu conda para poder importar elas.

Requirement already satisfied: nbformat in /home/carolina/miniconda3/lib/python3.13/site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /home/carolina/miniconda3/lib/python3.13/site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /home/carolina/miniconda3/lib/python3.13/site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/carolina/miniconda3/lib/python3.13/site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /home/carolina/miniconda3/lib/python3.13/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /home/carolina/miniconda3/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/carolina/miniconda3/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /home/carolina/miniconda3/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /home/carolina/miniconda3/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /home/carolina/miniconda3/lib/python3.13/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.0)
Note: you may need to restart the kernel to use updated packages.

## Carregando dados:
Para essa análise vamos usar um novo dataset o 03_netflix.csv, onde é mostrada algumas informações dos titulos adicionados na plataforma.

EXERCÍCIO:
carregue o arquivo csv no dataframe usando o pandas e mostre suas 20 primeira linhas.

In [15]:
# Sua resposta

Agora que já temos os dados carregados vc pode checar se os tipos dos dados estão correspondentes a realidade e se estão em tipos interesantes para se trabalhar. Por exemplo uma váriavel de preço pode ser salva na base de dados como uma string e assim vamos ter problemas ao tentar fazer uma média de preços por exemplo.

In [3]:
df.dtypes  #comando que mostra que tipo cada coluna armazena.

show_id           str
type              str
title             str
director          str
country           str
date_added        str
release_year    int64
rating            str
duration          str
listed_in         str
dtype: object

Como vc pode ver a maior parte das colunas guarda os seus valores em string, vamos ter que fazer algumas conversões, mas por enquanto vamos conhecer mais os dados.

Uma coisa que pode atrapalhar muito em uma analise de dados é a falta de dados, algumas informações podem simplemente não estarem escritas no dataset por falta de informação ou incoerrencia, mas como podemos varificar isso?

### Verificar valores ausentes:

In [4]:
df.isnull().sum()

show_id          0
type            37
title            1
director         7
country          4
date_added       1
release_year     0
rating           1
duration         2
listed_in        1
dtype: int64

EXERCÍCIO:
Quais colunas tem valores ausentes? Qual a coluna onde mais falta?

Sua resposta:

Existem várias maneiras de tratar esses valores ausentes, você pode apagar essas linhas do banco se foram poucas e não afetarem a análise que vc quer fazer, pode apagar a coluna porque ela não é relevante ou vc pode tentar preencher esse valor ausente de alguma forma.

EXERCÍCIO:
Faça uma breve pesquisa de formar de preencher valores ausentes em dataset para análise de dados e coloque suas anotações aqui.

Sua resposta:

Mas não é só porque um valor foi preenchido que isso que dizer que ele esta correto, mas como podemos verificar isso?

In [5]:
df["type"].unique() # vendo todos os tipos únicos presentes na coluna

<StringArray>
['Movie', 'TV Show', nan, 'Show', 'Tow', 'Tw', 'MV']
Length: 7, dtype: str

Na coluna tipo temos alguns tipos de programas mas alguns parecem que estão escritos errados o correto era categorizar entre 'Movie' e 'TV Show', como arrumar isso?
podemos modificar as registros nas linhas que parecem alteradas.

In [6]:
df["type"] = df["type"].replace({
    "Show": "TV Show",
    "Tow": "TV Show",
    "Tw": "TV Show",
    "MV": "Movie"
})

# voce pode rodar de novo a célula 18 e ver o resultado

OBSERVAÇÃO!! embora não seja incorreto substituir valores que parecem estar escritos de forma errada por categorias mais claras ou padronizadas, é importante lembrar que essa decisão é arbitrária. Ao fazer a substituição, estamos assumindo qual deveria ser o valor correto, mas não temos garantia de que essa interpretação está certa.

Por exemplo, ao trocar "MV" por "Movie" ou "Show" por "TV Show", estamos inferindo o significado com base no contexto do dataset. Em muitos casos isso faz sentido, mas ainda assim é uma suposição feita pelo analista.

Por isso, em situações reais de trabalho, o ideal é confirmar essas correções com a pessoa responsável pela base de dados ou com quem coletou as informações. Assim evitamos alterar dados de forma incorreta e garantimos que a padronização realmente representa o significado original dos registros.

## Converter Colunas

No dataset da Netflix, a coluna date_added representa a data em que o conteúdo foi adicionado à plataforma. No entanto, ao carregar o CSV, essa coluna geralmente é interpretada pelo pandas como texto (string).

Para poder trabalhar corretamente com datas — como extrair ano, mês ou fazer análises temporais — precisamos converter essa coluna para o tipo datetime.

Para isso utilizamos a função `pd.to_datetime()`.

EXERCICÍO:
Pesquise sobre a função `pd.to_datetime()` e explique com suas palavras o que ela faz.

Sua resposta:

In [7]:
# convertendo a coluna date_added para o tipo datetime
df["date_added"] = pd.to_datetime(df["date_added"])
print(df.dtypes)

show_id                    str
type                       str
title                      str
director                   str
country                    str
date_added      datetime64[us]
release_year             int64
rating                     str
duration                   str
listed_in                  str
dtype: object

## Criando uma nova variável
Agora que a coluna está no formato correto de data, podemos extrair partes específicas dessa informação.
Uma análise comum em datasets é observar em quais anos ocorreram mais eventos, como por exemplo quantos filmes foram adicionados à plataforma em cada ano.

Para isso, podemos criar uma nova coluna contendo apenas o ano em que o título foi adicionado e não a data completa.

In [8]:
# criando uma nova coluna com o ano em que o conteúdo foi adicionado
df["year_added"] = df["date_added"].dt.year
df

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in,year_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,Documentaries,2021.0
1,s3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",2021.0
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",2021.0
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"Children & Family Movies, Comedies",2021.0
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",2021.0
...,...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,2017-01-17,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas",2017.0
8786,s8798,TV Show,Zak Storm,Not Given,United States,2018-09-13,2016,TV-Y7,3 Seasons,Kids' TV,2018.0
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,2016-12-15,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",2016.0
8788,s8784,TV Show,Yoko,Not Given,Pakistan,2018-06-23,2016,TV-Y,1 Season,Kids' TV,2018.0
8789,s8786,TV Show,YOM,Not Given,Pakistan,2018-06-07,2016,TV-Y7,1 Season,Kids' TV,2018.0

Essa nova variável pode ser muito útil em análises futuras, por exemplo:

- identificar em quais anos mais conteúdos foram adicionados

- analisar o crescimento do catálogo ao longo do tempo

- comparar a quantidade de filmes e séries adicionados por ano


EXERCÍCIO:
Quais outras colunas novas poderiam ser criadas nesse dataset? Porque seria bom criar elas?

Sua resposta:

Outro problema que pode ser observado no dataset é que na coluna *duration* existem duas formas distintas de se contar o tempo: minutos e temporadas.
Essa mistura de informações dentro de uma mesma coluna pode dificultar algumas análises. Por exemplo, não faz sentido calcular uma média geral da coluna duration, pois estaríamos misturando minutos de filmes com temporadas de séries, que são medidas diferentes.
Uma forma comum de lidar com esse tipo de situação é separar a informação em novas variáveis, extraindo o número da duração e também o tipo de unidade (minutos ou temporadas). Dessa forma, conseguimos trabalhar com essas informações de maneira mais organizada e realizar análises mais adequadas para cada tipo de conteúdo.

#### DESAFIO
Observe alguns valores da coluna duration utilizando o método unique() ou head(). Em seguida, tente criar duas novas colunas no dataset:
- uma coluna contendo apenas o número da duração
- outra coluna indicando se a duração está em minutos ou em temporadas
Depois de criar essas colunas, verifique o resultado mostrando algumas linhas do dataset para confirmar se a separação foi feita corretamente.

# Visualização de Dados
A visualização de dados é uma etapa fundamental da análise exploratória de dados. Ela consiste em representar informações por meio de gráficos e elementos visuais, permitindo compreender padrões, tendências e relações presentes nos dados de forma mais intuitiva.

Enquanto tabelas e números podem ser difíceis de interpretar rapidamente, gráficos ajudam a transformar grandes volumes de dados em representações visuais mais fáceis de entender. Isso permite identificar comportamentos que muitas vezes não seriam percebidos apenas observando os valores brutos.

In [9]:
# quantidade de Filmes vs Séries
df["type"].value_counts()  # dado bruto
df["type"].value_counts().reset_index()

      type  count
0    Movie   6124
1  TV Show   2629

In [10]:
type_counts = df["type"].value_counts().reset_index()

fig = px.bar(
    type_counts,
    x="type",
    y="count",
    labels={
        "type": "Tipo de conteúdo",
        "count": "Quantidade"
    },
    title="Quantidade de Filmes e Séries no Dataset"
)

fig.show() # grafico bonito e colorido

In [11]:
conteudo_por_ano = df["year_added"].value_counts().sort_index()

fig = px.line(
    conteudo_por_ano,
    labels={"value": "Quantidade", "year_added": "Ano"},
    title="Quantidade de conteúdos adicionados por ano"
)

fig.show()

In [12]:
top_paises = df["country"].value_counts().head(10)

fig = px.bar(
    top_paises,
    labels={"value": "Quantidade", "country": "País"},
    title="Países com mais conteúdos no dataset"
)

fig.show()

EXERCÍCIO:
Usando os gráficos acima como exemplo tente fazer um gráfico de alguma métrica. 
Se ficar dificíl uma a nova biblioteca [Plotly](https://plotly.github.io/plotly.py-docs/generated/plotly.html) você pode ler a documentação dela para aprender mais.

In [13]:
# Sua resposta

## Interpretação EXECÍCIO

Após realizar a limpeza dos dados e construir as primeiras visualizações, é importante lembrar que o objetivo da análise de dados não é apenas gerar gráficos, mas interpretar as informações que eles apresentam.

A partir do gráfico criados observe atentamente os resultados e reflita sobre o que eles podem indicar. 
- O que você observa no gráfico?
- Os resultados eram esperados ou te surpreenderam?
- Que tipo de conclusões podem ser tiradas a partir dessa visualização?
- Que tipo de outras hipoteses você gostaria de testar fazendo outros gráficos?

SUA RESPOSTA: